# Generated by Django 5.2 on 2025-05-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hat',
            name='is_available',
        ),
    ]
