# Generated by Django 5.2 on 2025-05-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats', '0002_remove_hat_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hat',
            name='price',
            field=models.IntegerField(),
        ),
    ]
