# Generated by Django 5.2 on 2025-05-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats', '0003_alter_hat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
