# Generated by Django 5.2 on 2025-05-04 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats', '0004_hat_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hat',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='hat',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
