# Generated by Django 5.2 on 2025-05-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats', '0009_remove_customer_user_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hat',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HatImage',
        ),
    ]
