# Generated by Django 5.2 on 2025-05-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats', '0010_alter_hat_name_delete_hatimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_active',
        ),
        migrations.AddField(
            model_name='cart',
            name='hats',
            field=models.ManyToManyField(to='hats.hat'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
